let compIndex = 0;
let verseIndex = 0;

const complimentList = [
"You are the best part of my day, every single day.",
"I love how you always stay true to yourself.",
"You have a way of making everyone around you feel special.",
"I am constantly in awe of your strength.",
"You’re not just a student; you’re a visionary.",
"Your passion is what makes you so beautiful.",
"The way you handle pressure is a masterclass in grace.",
"I hope you see yourself the way I see you.",
"You are a light that never fades.",
"I’m so lucky to be the one you choose to share your life with.",
"Your intelligence is one of your most attractive qualities.",
"You make even the hardest days feel worth it.",
"I love that I can always count on you.",
"You are my favorite place to be.",
"You’re doing a great job, even when you don't feel like it.",
"I love how your mind finds beauty in the small things.",
"You are the peace I didn't know I was looking for.",
"I’m so proud of the way you balance everything.",
"Your kindness is a superpower.",
"You have a heart that matches your beautiful smile.",
"I love how you never settle for less than your best.",
"You are my favorite person to grow with.",
"The world is better because you're in it.",
"You make me want to be a better man.",
"Your laugh is the sound of home to me.",
"I believe in your dreams as much as you do.",
"You are incredibly resilient.",
"You have such a calming presence.",
"I love the way you love.",
"You are a rare and precious soul.",
"Don't ever let the world change your kind heart.",
"You are far more than enough.",
"Your potential is literally limitless.",
"I love seeing the world through your eyes.",
"You are my greatest adventure.",
"You are the definition of elegance and strength.",
"I’m so glad we get to do life together.",
"Your energy is absolutely magnetic.",
"I love how you stand up for what you believe in.",
"You are a masterpiece.",
"I cherish every conversation we have.",
"You are the dream I never want to wake up from.",
"Your bravery inspires me more than you know.",
"You are a blessing to everyone who knows you.",
"I love the way you challenge me to think deeper.",
"You are the most beautiful person I know, inside and out.",
"I’m always in your corner, no matter what.",
"You are simply unforgettable.",
"I love your 'never-give-up' attitude.",
"You’ve been on my mind all day."
];

const verseList = [
    "Psalm 139:14 - I praise you because I am fearfully and wonderfully made.",
    "Proverbs 31:25 - She is clothed with strength and dignity; she can laugh at the days to come.",
    "Philippians 4:13 - I can do all things through Christ who strengthens me.",
    "Joshua 1:9 - Be strong and courageous. Do not be afraid; the Lord is with you.",
    "Psalm 46:5 - God is within her, she will not fall; God will help her at break of day.",
    "Jeremiah 29:11 - For I know the plans I have for you, plans to give you hope and a future.",
    "Isaiah 40:31 - But those who hope in the Lord will renew their strength.",
    "Proverbs 3:5 - Trust in the Lord with all your heart and lean not on your own understanding.",
    "Song of Songs 4:7 - You are altogether beautiful, my darling; there is no flaw in you.",
    "Psalm 23:1 - The Lord is my shepherd, I shall not be in want.",
    "Romans 8:31 - If God is for us, who can be against us?",
    "Matthew 11:28 - Come to me, all you who are weary and burdened, and I will give you rest.",
    "Psalm 34:18 - The Lord is close to the brokenhearted and saves those who are crushed in spirit.",
    "1 Corinthians 16:14 - Do everything in love.",
    "John 14:27 - Peace I leave with you; my peace I give you. Do not let your hearts be troubled.",
    "Zephaniah 3:17 - The Lord your God is in your midst; He will quiet you by His love.",
    "Psalm 121:1 - I lift up my eyes to the mountains—where does my help come from? It comes from the Lord.",
    "Proverbs 4:23 - Above all else, guard your heart, for everything you do flows from it.",
    "2 Timothy 1:7 - For God has not given us a spirit of fear, but of power and of love and of a sound mind.",
    "Psalm 27:1 - The Lord is my light and my salvation—whom shall I fear?",
    "Exodus 14:14 - The Lord will fight for you; you need only to be still.",
    "Psalm 119:105 - Your word is a lamp for my feet, a light on my path.",
    "Romans 15:13 - May the God of hope fill you with all joy and peace as you trust in him.",
    "1 Peter 5:7 - Cast all your anxiety on him because he cares for you.",
    "Psalm 37:4 - Delight yourself in the Lord, and he will give you the desires of your heart.",
    "Lamentations 3:22 - Because of the Lord’s great love we are not consumed, for his compassions never fail.",
    "Matthew 19:26 - With man this is impossible, but with God all things are possible.",
    "Psalm 143:8 - Let the morning bring me word of your unfailing love, for I have put my trust in you.",
    "Isaiah 41:10 - So do not fear, for I am with you; do not be dismayed, for I am your God.",
    "Psalm 46:10 - Be still, and know that I am God.",
    "Hebrews 11:1 - Now faith is confidence in what we hope for and assurance about what we do not see.",
    "Proverbs 16:3 - Commit to the Lord whatever you do, and he will establish your plans.",
    "Psalm 91:4 - He will cover you with his feathers, and under his wings you will find refuge.",
    "John 15:12 - My command is this: Love each other as I have loved you.",
    "Psalm 107:1 - Give thanks to the Lord, for he is good; his love endures forever.",
    "Romans 8:28 - And we know that in all things God works for the good of those who love him.",
    "Psalm 138:8 - The Lord will fulfill his purpose for me; your love, Lord, endures forever.",
    "Numbers 6:24 - The Lord bless you and keep you.",
    "Proverbs 31:30 - Charm is deceptive, and beauty is fleeting; but a woman who fears the Lord is to be praised.",
    "Isaiah 43:2 - When you pass through the waters, I will be with you.",
    "1 Thessalonians 5:11 - Therefore encourage one another and build each other up.",
    "Psalm 16:11 - You fill me with joy in your presence, with eternal pleasures at your right hand.",
    "Colossians 3:23 - Whatever you do, work at it with all your heart, as working for the Lord.",
    "Psalm 56:3 - When I am afraid, I put my trust in you.",
    "2 Corinthians 12:9 - My grace is sufficient for you, for my power is made perfect in weakness.",
    "James 1:5 - If any of you lacks wisdom, you should ask God, who gives generously to all.",
    "Psalm 34:8 - Taste and see that the Lord is good; blessed is the one who takes refuge in him.",
    "Ephesians 3:20 - God is able to do immeasurably more than all we ask or imagine.",
    "Proverbs 18:10 - The name of the Lord is a fortified tower; the righteous run to it and are safe.",
    "Psalm 62:6 - Truly he is my rock and my salvation; he is my fortress, I will not be shaken.",
    "Hebrews 13:5 - Never will I leave you; never will I forsake you.",
    "Deuteronomy 31:6 - Be strong and courageous. Do not be afraid, for the Lord your God goes with you.",
    "Psalm 118:24 - The Lord has done it this very day; let us rejoice today and be glad.",
    "1 John 4:19 - We love because he first loved us.",
    "Psalm 147:3 - He heals the brokenhearted and binds up their wounds.",
    "Isaiah 26:3 - You will keep in perfect peace those whose minds are steadfast, because they trust in you.",
    "Proverbs 3:6 - In all your ways submit to him, and he will make your paths straight.",
    "Matthew 5:14 - You are the light of the world. A town built on a hill cannot be hidden.",
    "Psalm 18:2 - The Lord is my rock, my fortress and my deliverer.",
    "Galatians 5:22 - But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.",
    "Psalm 103:1 - Praise the Lord, my soul; all my inmost being, praise his holy name.",
    "Philippians 4:6 - Do not be anxious about anything, but in every situation, by prayer, present your requests to God.",
    "Song of Songs 2:10 - My beloved spoke and said to me, 'Rise up, my darling, my beautiful one, come with me.'",
    "Psalm 30:5 - Weeping may stay for the night, but rejoicing comes in the morning.",
    "Romans 12:12 - Be joyful in hope, patient in affliction, faithful in prayer.",
    "Psalm 55:22 - Cast your cares on the Lord and he will sustain you.",
    "1 Corinthians 13:4 - Love is patient, love is kind. It does not envy, it does not boast, it is not proud.",
    "Micah 6:8 - And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God.",
    "Psalm 32:8 - I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.",
    "Hebrews 10:24 - And let us consider how we may spur one another on toward love and good deeds.",
    "John 16:33 - In this world you will have trouble. But take heart! I have overcome the world.",
    "Psalm 84:11 - For the Lord God is a sun and shield; the Lord bestows favor and honor.",
    "Proverbs 31:10 - A wife of noble character who can find? She is worth far more than rubies.",
    "Matthew 6:33 - But seek first his kingdom and his righteousness, and all these things will be given to you as well.",
    "Psalm 119:114 - You are my refuge and my shield; I have put my hope in your word.",
    "Mark 10:27 - Jesus looked at them and said, 'With man this is impossible, but not with God.'",
    "Psalm 145:18 - The Lord is near to all who call on him, to all who call on him in truth.",
    "Ephesians 4:32 - Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.",
    "Proverbs 17:17 - A friend loves at all times.",
    "Psalm 126:3 - The Lord has done great things for us, and we are filled with joy.",
    "Colossians 3:14 - And over all these virtues put on love, which binds them all together in perfect unity.",
    "Psalm 136:1 - Give thanks to the Lord, for he is good. His love endures forever.",
    "1 Peter 4:8 - Above all, love each other deeply, because love covers over a multitude of sins.",
    "Psalm 20:4 - May he give you the desire of your heart and make all your plans succeed.",
    "Isaiah 54:10 - Though the mountains be shaken... my unfailing love for you will not be shaken.",
    "Psalm 94:19 - When anxiety was great within me, your consolation brought me joy.",
    "2 Corinthians 5:7 - For we live by faith, not by sight.",
    "Proverbs 15:1 - A gentle answer turns away wrath.",
    "Psalm 100:5 - For the Lord is good and his love endures forever; his faithfulness continues through all generations.",
    "Romans 5:5 - And hope does not put us to shame, because God’s love has been poured out into our hearts.",
    "Psalm 40:1 - I waited patiently for the Lord; he turned to me and heard my cry.",
    "1 Chronicles 16:11 - Look to the Lord and his strength; seek his face always.",
    "Psalm 115:14 - May the Lord cause you to flourish, both you and your children.",
    "Ephesians 2:8 - For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God.",
    "Psalm 34:10 - Those who seek the Lord lack no good thing.",
    "Proverbs 31:26 - She speaks with wisdom, and faithful instruction is on her tongue.",
    "Philippians 1:6 - He who began a good work in you will carry it on to completion until the day of Christ Jesus.",
    "Psalm 33:22 - May your unfailing love be with us, Lord, even as we put our hope in you.",
    "Revelation 21:4 - He will wipe every tear from their eyes.",
    "Psalm 121:8 - The Lord will watch over your coming and going both now and forevermore."
];

function showItem(type) {
    const textElement = document.getElementById('display-text');
    let selectedText = "";

    textElement.style.opacity = 0;

    setTimeout(() => {
        if (type === 'compliments') {
            selectedText = complimentList[compIndex];
            compIndex = (compIndex + 1) % complimentList.length;
        } else {
            selectedText = verseList[verseIndex];
            verseIndex = (verseIndex + 1) % verseList.length;
        }

        textElement.innerText = selectedText;
        textElement.style.opacity = 1;
        textElement.classList.add('fade-in');

        setTimeout(() => textElement.classList.remove('fade-in'), 500);
    }, 300);
}
